sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
  - 4
  - 5
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8

env:
  - PHANTOMJS_BIN=/home/travis/build/decipherinc/angular-loggly-mixin/node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs
