os:
  - linux
sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
  - 4
  - 5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i
env:
  - PHANTOMJS_BIN=/home/travis/build/decipherinc/angular-loggly-mixin/node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs
