sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
- 4
- 5
compiler: clang-3.6
env:
  matrix:
  - CXX=clang-3.6
  global:
    secure: wi68IdQd+zqp9bV43xXf35xL2Cciw35m6iAWp0vSy7Uyg96e2zfK22EB0FhuktrqZLsyMmvl5Gl38MYULdn+VhuIBXJZn0JtriEWVFoI+MrNCEG0Q981yg+9+mx6uojlLpmFljeov5KFxwCQlXGkLnwpphFa6aWjUyHPlhlBMl5EfuXnfN+vs3xeinDJEAeO2mQAAg3kkSVdTFIpx2pzzo1dCGjc0QahiKpLjdXdrJ4KGqqYTwRI102NeqCetreF07lCVmRGGe9j/35dNlKoVr78seDyDuJqnA6RMpYDmNmUJD2HSU8nG/edZzZc4LRi12zcf+XzAt5jpQ1gNShJ/7HnLPLG7cyg79iiE7kEMDiQ+t8R6IfgfK6/td+ZK8O/DzqSAB1YUxweU0JsGcHOwG5TuCjD22d/a0EpfaZ7llLWBUCQ24+Zrx1ERD+wAEvee2k2W9Ir/194qxUPCsGLN7Jg3DSjROnojLvfk2uof93u8hBcSkc/u+74nJBvwLPuWHESpP3EMghhC68quNkEApxbQDzgyvqKAaAUtLx/zUSwaEcr286cIuSHZrjsIz0S21+78vSScjnpB4lDE12TnW0vApNKkubtJbGW4Km3YwOz1OAgN6pu0JABempxIbfUuiMNpYeHvFxz8MNFj0VrO1inYyyWYsnwkKYC9pfonAU=
addons:
  code_climate:
    secure: YLpI3sbSQrrKMKCMKbCj2Lz9zPN2AieebTdfv7TgX07TMxdNb8DWzY/7QXDf7zEe/GTJbBaY/67M5AkckcRmEekfUSaUINdf9MbTPXwvfF/61bkXlkb9AIEmkOUV8VJFA4Ndcn1HbUhjTzi2WtLT9w6d/GR6B+rTqSRfty5IzI4++OOPM0Kqkct/XHY7CmGplHwZp/VGsPg8csL3lD+wUZvCQTy2UAKRHtscq/29g8PIXi+jwpg3soumBe3SGjOoXuhq2WVfv4GoTYaQd5zeME6bebyGEG1G6/moypv869+ZEXNAvQG+XJxjMWa9Xs9gMsrvL/1XFLFw4LJ9Nzf2ybTV+NgETCCeNfyS/Fqh71M1mY8kMoSwFtaO4UABmpAjYIE/nyz4jwyOasKy7MiVGY0/V1REdxVzE5TwV1NwoAjDOP8MkqQSK1h2KWIrT5Rc9vv4G1krI+kuDwjOtJyw+8HqmO1EsZ3dmZKAZ6HqDyQkqU0GgLIlMk/qCSKU1dMC5sBAhsvub3hDiIWB9mRC9jUdBrAZx6PNBZ+viXZ2LnijFxD+qGipXyCmkUAtb8Mhk9yZEo8yilDuNykU563Ht1AQREHark/ZRjrBOmqakOSUn2dcTsGPTzsf8YiRTx7vPB+7MGY3F99F8A8m8CdgVtcaCmCLJZTSHA0rLJxf5r4=
notifications:
  email: false
  pushover:
    api_key:
      secure: ScxGZ1lFtqLuQwBS9ygVOar/SFdJ8d/pL1uQunzwYdoE0i7qdzFYmcoMtz7X+x7btRI5OfrudVS6njGi/uiWdlcw0hmATmKK9hIPH1LBh4/RexPkU2RtXl4MZ5InA38WjftDSIiczzaOvjHhfslUzwn6QTZaImVjYp8cQxl8QvxD8BKdI8LLMjc8u71XNpl8vqLt/NinQE9INqlJ1h6rPFLyY0Wc4Lt19Hubg1u+NFbafnAsR7iZ1p4ziG3lTEqSsRoZTOvYv0lyyFlpRVYOPmCyCH25BJy7dch8claBrBQkGmh8lClj6lRdc/+FEcuzdhaIiyGx2WsPai09dv86NSLsxiwtRxe/VVGMqqH3PUISBI6cASYhFS6PyI+mEl7Ff+2RBvtKLbXpm4cJIPj3ewM0tFkmMgUanyJ54+vEYS+Vz/Q+Uy3OYY7ovNX9E5Fm/LrQj/IBVu+v1diIxgx2yz/KL4qDKjvop7s8hyBBMn81xRVXwCTbZ0F8X90hzeKy9XY8j4QUhvhPmmq3xBxeKVquR8C7qRO/W8h3AAowfEOeZ2teceYh6bZPdXJaBG8uApAjm7AGzprIEe+TF2ZkdkWxq0bW4PvEqkI7meFyonRgKHwx3eep83rRIvmVkYeKED33WnJyOGu6CSJKQGto1lPsjDkzwbCqj0CX4BCvxn8=
    users:
    - secure: MMwVE66SU1IiMBw1MinlparwXwYOjwCxDK/bHBQxVD80y4Z8iGMKSE8YoJH7/aWZ7fAFTArOYzkvJOPn+d773lnHPQBAAwKjcVcLMoL4TrxSaw6UmixRuUdKcPSOpnp4huLANi6dOwkFJHvQTn8n4ARqlq1kOvpYYoJ66r7ALYj06Wm2c5m+68IKxLH2ojQz9TvCwii+1zjGHQslAaJlVZ1Y3iByZfsrFtRdaIeqe1233Qd/TRG1k/HSqqqX21Le7m8oEjixFqS7sy4fPm0iphpVCinMUdjvQk9hJUuPvvf//IKtP8pqy/ixIQPGM7Mtb/3zCwqs+Q6wVnOcjSfUzV71GqNXdSPKjVx+7oHkHn/lhbph/zW6VeTrkQyaGBcqsy1JZvAlzgg9LJK+oLN5EKBi24qcguw2BpnZbTc2cjKN5tJBXK50mMUMh2I0FfdGp/3e3qiQ/xSHGrdNXiMcpFBge85wWJtrxc6yHugGAu/nFl6DFML7TqNkWHVV41FS+COUI/KToalwzcv1SnUk72YaNSc/JSMY43b3igI6TzJ7vJFeCyjxDyNaitVFkgXiI4dtLE4V9SWD/XwK1L8vtMIj7iPLKctGuO4DbfAicqw6IE+h3qhTM9xnSw7aWHeBXvuXLdP4OSBVpakBmgM+ACflDHQz3v540W3vEX9siTs=
after_script:
- codeclimate-test-reporter < coverage/lcov.info
- node_modules/.bin/coveralls < coverage/lcov.info
